### ISSUE TITLE
Ruby 3 support: URI.unescape

### ISSUE THREAD

**Issue by benjamin-ltr** [ilovepdf/ilovepdf-ruby#12]
On ruby 3, we have some errors using the ilovepdf gem:

```
undefined method `unescape' for URI:Module
```

This method was deprecated on ruby 2.7 and removed on ruby 3.
Also, the README file specifies that this gem requires Ruby 2.6 or greater but the travis Ci is configured for ruby 2.5.0 only.
It can be good to specify multiple ruby versions for the CI runs.

Thanks

**Comment by maztch** [comment]
Thanks for the report and help

**Comment by benjamin-ltr** [comment]
Thanks for merging the fix.

Can you release a new version of the gem?

**Comment by maztch** [comment]
It should be published
