### ISSUE TITLE
Fix bad setter name on pdfjpg class

### ISSUE THREAD

**Issue by benjamin-ltr** [ilovepdf/ilovepdf-ruby#14]
After installing the latest version, I now have a new bug on the pdfjpg class:
```
 ArgumentError:
       wrong number of arguments (given 0, expected 1)
```

The problem comes from a badly name setter method introduced by https://github.com/ilovepdf/ilovepdf-ruby/commit/305e551f7e187c06efc9ec709f104a987b713328 (not released with the previous version)

I also generated the code coverage for this gem and it's lacking unit tests:

![Screenshot 2024-05-16 at 14 35 06](https://github.com/ilovepdf/ilovepdf-ruby/assets/37066221/4c335a65-d67b-4d78-a837-4d7002606320)

**Comment by naydenovg** [comment]
@maztch could you check out this PR, please?

**Comment by benjamin-ltr** [comment]
Thanks for merging the fix.

Can you release a new version of the gem?
